### ISSUE TITLE
Uploading of dataset Datetime type

### ISSUE THREAD

**Issue by saitoh183** [DevScope/powerbi-powershell-modules#10]
When i use Out-PowerBI to upload the result for the column that are set to datetime cannot be used in Hierarchy (by month, yeah, etc)

When i upload the CVS of the same dataset using GetData from PowerBi, i get the options. (same In PowerBi Desktop)

using Out-PowerBI:

![image](https://cloud.githubusercontent.com/assets/1534197/13682903/ed1690bc-e6d1-11e5-9ee8-4ceba7947ccc.png)

Using GetData

![image](https://cloud.githubusercontent.com/assets/1534197/13683006/711e5d7c-e6d2-11e5-8f39-a956f24e995f.png)

I also tried using Out-PowerBi with the CSV and its the same problem.

Is this a limitation or there is something im missing?

**Comment by saitoh183** [comment]
if it can help, here is my CSV
[AllRequestTable..txt](https://github.com/DevScope/powerbi-powershell-modules/files/167993/AllRequestTable.txt)

**Comment by RuiRomano** [comment]
Hi,

You are right, but it seems to be a limitation on the PowerBI API, please open a UserVoice request here:

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/6802457-uservoice

As an alternative you could create those columns in powershell and upload them with out-powerbi, ex:

Import-Csv $file.FullName | select @{Label="Year";Expression={$_.Closed.Year}}, *

Thanks
