### ISSUE TITLE
Error - Could not load file or assembly

### ISSUE THREAD

**Issue by treymorgan** [DevScope/powerbi-powershell-modules#11]
On two machines, after executing the following in PowerShell ISE as administrator I receive the following error. One machine is Win 8.1 and the other is Win 10.  Any idea why it cannot load Microsoft.IdentityModel.Clients.ActiveDirectory.dll?  I tried to import the module from both GitHub and the powershell gallery.  I'm very excited about using your module.  Thank you for your support and assistance.

Executing this in PowerShell ISE
Set-ExecutionPolicy -ExecutionPolicy Unrestricted
Install-Module powerbips
Import-Module powerbips

I receive this error on two different machines:

Import-Module : Could not load file or assembly 
'file:///C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\powerbips\Microsoft.IdentityModel.Clients.ActiveDirectory.dll' or one of its dependencies. Operation is not 
supported. (Exception from HRESULT: 0x80131515)
At line:5 char:1
+ Import-Module powerbips
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by RuiRomano** [comment]
Hi Trey, just tested on a new machine (surface pro) and worked ok.

From your log I'm seeing that powershell is trying to load the module from c:\Windows but he should be loading from here:

C:\Program Files\WindowsPowerShell\Modules\PowerBIPS\1.2.0.7

Please ensure that you have the latest Windows Management Framework (WMF) 5.0:

https://www.powershellgallery.com/

Also confirm that you have .net 4.5 installed and your powershell runtime is running on .net 4:

<supportedRuntime version="v4.0" />

Thanks
