### ISSUE TITLE
No error or status message with datarefresh

### ISSUE THREAD

**Issue by RonaldMussche** [DevScope/powerbi-powershell-modules#17]
I am using this the refresh the dataset in power bi. It works pretty well and simple so thanks. But I don't get an error or status message. So i have to check in powerBI if the data is refrehed. And it hard to find out why it fails. Is there a way to catch the status/ Error?

**Comment by RuiRomano** [comment]
Hi, yes it's possible. Check the cmdlet: "Get-PBIDatasetRefreshHistory" it uses this api: https://msdn.microsoft.com/en-US/library/mt784655.aspx
