### ISSUE TITLE
Crashes Windows PowerShell ISE

### ISSUE THREAD

**Issue by neuroklinik** [DevScope/powerbi-powershell-modules#18]
I've run two commands from this module, "Get-PBIAuthToken" and "Out-PowerBI", and while both complete Windows PowerShell ISE crashes immediately thereafter. Can't even move the ISE window.

**Comment by RuiRomano** [comment]
Strange, does this happen on a normal powershell window? Or just ISE?

**Comment by neuroklinik** [comment]
Yep. Turns out it was just the ISE. Inconvenient, but certainly not a showstopper. Thank you for getting back to me!

**Comment by edwardmiles** [comment]
I had this problem, turned out it was caused by 2 factor authentication. If you have that turned on, and can turn it off the problem should go away
