### ISSUE TITLE
Release latest code to powershell gallery

### ISSUE THREAD

**Issue by znoke** [DevScope/powerbi-powershell-modules#25]
Are you planning to release the latest code the powershell gallery any time soon? There are several changes (specifying the group/workspace in some cmdlets and a few new cmdlets) that I would like to use.

Thanks.

**Comment by RuiRomano** [comment]
Yes, will do it today.



Enviado a partir do meu smartphone Samsung Galaxy.


-------- Mensagem original --------
De: Zeno Dierick <notifications@github.com>
Data: 08/02/18 10:19 (GMT+00:00)
Para: DevScope/powerbi-powershell-modules <powerbi-powershell-modules@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [DevScope/powerbi-powershell-modules] Release latest code to powershell gallery (#25)


Are you planning to release the latest code the powershell gallery any time soon? There are several changes (specifying the group/workspace in some cmdlets and a few new cmdlets) that I would like to use.

Thanks.

**Comment by RuiRomano** [comment]
Done, version 1.3.1.0.

Thanks for the alert
