### ISSUE TITLE
"Get-PBIDatasetParameters", "Set-PBIDatasetParameters" cmdlets not present in latest module

### ISSUE THREAD

**Issue by tushu1984** [DevScope/powerbi-powershell-modules#30]
"Get-PBIDatasetParameters", "Set-PBIDatasetParameters" not present in latest 1.3.3.0 module
even after installing these 2 cmdlets not getting imported.

**Comment by joanavb** [comment]
Hi,
We've just updated the module to version 1.3.4.0 which already contains the cmdlets you mentioned.

Thank you for the feedback.
