### ISSUE TITLE
Convert-PowerBIDesktopToASTabular fails if there are referenced queries

### ISSUE THREAD

**Issue by GaretAnderson** [DevScope/powerbi-powershell-modules#51]
Hello, Convert-PowerBIDesktopToASTabular (both using pbit or desktop app) fails to generate a valid model.bim if the pbix uses referenced queries. The referencing query expression is written as an single space instead of the actual query found in the pbix. 

`        "partitions": [
          {
            "name": "Referenced Table1-9200782a-7d17-4f56-a077-b910dbc65797",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": " "
            }
          }
        ],`

Attached is a pbix with a single column empty table, not loaded to model, and a query that references the former and loads to model. Also in the same zip is the results from  Convert-PowerBIDesktopToASTabular.

[Reference Test.zip](https://github.com/DevScope/powerbi-powershell-modules/files/2818984/Reference.Test.zip)

**Comment by GaretAnderson** [comment]
Update, I see (and updated to) a commit from a week ago to fix this and it does partially resolve the aforementioned issue but it surfaces another related problem where the referenced query that is not loaded is not created in the model.bim

Deployments will thus fail with this error:
The JSON DDL request failed with the following error: Failed to save modifications to the server. Error returned: 'Expression in partition 'Referenced Table1-9200782a-7d17-4f56-a077-b910dbc65797' in table 'Referenced Table1' references unknown variable or function 'Table1'.
'..

**Comment by GaretAnderson** [comment]
This is the resulting model.bim from the latest module update, missing the expression for Table1 (a query resulting in a table that is not loaded) 

[model.bim.zip](https://github.com/DevScope/powerbi-powershell-modules/files/2819194/model.bim.zip)

**Comment by GaretAnderson** [comment]
Latest push worked on my simple sample but failed on my IRL file because ' in ' appeared in a column name. Conceivably this would be an issue anywhere that string appears so I created a regex search string and have a pull request here [https://github.com/DevScope/powerbi-powershell-modules/pull/53](url) for it.

**Comment by fpvmorais** [comment]
I have merged your code. With my samples it works as it should. If everything is alright from your side please close the issue.

Thank you for your help :)

**Comment by GaretAnderson** [comment]
I've submitted another fix and a couple changes. Please review and accept the pull request, thank you!
