### ISSUE TITLE
-pbiDesktopWindowName

### ISSUE THREAD

**Issue by AnnibalAbreu** [DevScope/powerbi-powershell-modules#52]
can someone explain what is this? I tried to use a .pbix file but it does not work.

**Comment by fpvmorais** [comment]
That switch makes the script look for a open window with a certain name.

If you have a pbix file named "MyPowerBIFile.pbix" you should open the file in powerbi desktop and then run the script in the powershell command line with a command like this:

`Convert-PowerBIDesktopToASTabular -pbiDesktopWindowName "*MyPowerBIFile*" -outputPath c:\Temp\TestSSAS\ `

The script only works when you have an open powerbi file.

Hope it helps.
