### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alexm186** [DevScope/powerbi-powershell-modules#58]
You could remove the ADAL libraries from your module and add AzureRM.profile as a dependency. 
Right now, PowerBIPS can't be used with the latest AzureRM because PowerBIPS uses an older version of ADAL.

**Comment by RuiRomano** [comment]
Hi Alex, not sure if adding a dependency to AzureRM.Profile would be an overhead and if has the same authentications I use on PowerBIPS like the devicecode authentication or client secret.

But I can update the ADAL dll for the lastest version, will that work for you?

**Comment by alexm186** [comment]
Yes, that would be great. Keep. in mind that some types and methods have changed, you need to update the get token function as well.

**Comment by RuiRomano** [comment]
Hi Alex, published a new version of the module with the new ADAL dlls.
