### ISSUE TITLE
Problem with Creating Data Sets

### ISSUE THREAD

**Issue by mattmcnabb** [DevScope/powerbi-powershell-modules#6]
I am attempting to create a new data set with multiple tables. When I do this, some tables return a 400 bad request error and I'm not certain why.

This one works:
```Powershell
@{
    name    =  "ClientConnection"
    columns = @(
        @{ name = "Date";       dataType = "DateTime" },
        @{ name = "ClientType"; dataType = "String" },
        @{ name = "Count";      dataType = "Int64" }					
     )
 }
```
But this one doesn't:
```Powershell
@{
    name    = "OneDrivesDeployed"
    columns = @(
        @{ name = "Date";     datatype = "DateTime" },
        @{ name = "Active";   datatype = "Int64" },
        @{ name = "Inactive"; datatype = "Int64" }
    )
}
```
What's the functional difference here? This could just be an issue with constraints in PowerBI and not an issue with the module itself, but I'm unable to find why this might fail.

**Comment by mattmcnabb** [comment]
Nevermind, I forgot that this is getting translated to JSON, which has strict capitalization rules. I see now that in the second one 'datatype' should have been 'dataType'. Sorry!

**Comment by RuiRomano** [comment]
Sorry for the late reply, glad you solved it ;)
