### ISSUE TITLE
Publish the PowerBIPS module on the psgallery

### ISSUE THREAD

**Issue by Stijnc** [DevScope/powerbi-powershell-modules#8]
Would it be possible to publish the module on https://www.powershellgallery.com/ ?

**Comment by RuiRomano** [comment]
Hi Stinjnc,

Great tip, its published! https://www.powershellgallery.com/packages/PowerBIPS/

Also need to include the dll "Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll" to make it work.

Thanks
